//
//  Boards.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class Boards: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _boardId: String?
    var _board: String?
    var _boardName: String?
    var _creationTime: NSNumber?
    var _creatorId: String?
    var _creatorName: String?
    var _pieces: String?
    
    class func dynamoDBTableName() -> String {

        return "bank-mobilehub-787901168-Boards"
    }
    
    class func hashKeyAttribute() -> String {

        return "_boardId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_boardId" : "boardId",
               "_board" : "board",
               "_boardName" : "boardName",
               "_creationTime" : "creationTime",
               "_creatorId" : "creatorId",
               "_creatorName" : "creatorName",
               "_pieces" : "pieces",
        ]
    }
}
