//
//  ResultsTable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class ResultsTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _userUUID: String?
    @objc var _username: String?
    @objc var _timeStamp: NSNumber?
    @objc var _boardHash: String?
    @objc var _boardName: String?
    @objc var _moveCount: NSNumber?
    @objc var _moves: [String]?
    @objc var _notEnoughPieces: NSNumber?
    @objc var _playID: String?
    @objc var _shuffledPieces: [String]?
    @objc var _won: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "bank-mobilehub-787901168-ResultsTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userUUID"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_timeStamp"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userUUID" : "userUUID",
               "_username" : "username",
               "_timeStamp" : "timeStamp",
               "_boardHash" : "boardHash",
               "_boardName" : "boardName",
               "_moveCount" : "moveCount",
               "_moves" : "moves",
               "_notEnoughPieces" : "notEnoughPieces",
               "_playID" : "playID",
               "_shuffledPieces" : "shuffledPieces",
               "_won" : "won",
        ]
    }
}
