//
//  UserCreatedBoardsTable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class UserCreatedBoardsTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _creatorUUID: String?
    var _timeStamp: NSNumber?
    var _boardHash: String?
    var _boardName: String?
    var _creatorName: String?
    var _pieces: String?
    
    class func dynamoDBTableName() -> String {

        return "bank-mobilehub-787901168-UserCreatedBoardsTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_creatorUUID"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_timeStamp"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_creatorUUID" : "creatorUUID",
               "_timeStamp" : "timeStamp",
               "_boardHash" : "boardHash",
               "_boardName" : "boardName",
               "_creatorName" : "creatorName",
               "_pieces" : "pieces",
        ]
    }
}
